name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
      - name: Cloning repository
        uses: actions/checkout@v3
      - name: Python Install
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Poetry Install
        run: pipx install poetry
      - name: Dependencies Install
        run: poetry install --no-root
      - name: Run tests
        run: poetry run task test